---
kind: pipeline
name: default

environment:
  GITHUB_ORG: hukuruio
  GITHUB_REPO: hukurio-docker-compose

steps:
  - name: build
    image: hukuruio/docker-compose:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - make

  - name: push-image
    image: hukuruio/docker-compose:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_HUB_TOKEN:
        from_secret: docker_hub_token
      DOCKER_USERNAME:
        from_secret: docker_hub_username
    commands:
      - make release
    when:
      status:
        - success
      branch:
        include:
          - develop
      event:
        include:
        - push

  - name: tag-git-repo
    image: hukuruio/git:latest
    environment:
      GITHUB_USER:
        from_secret: github_user
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - python utils/manage.py create-release -b $${DRONE_COMMIT_BRANCH} -sha $${DRONE_COMMIT_SHA}
    when:
      status:
        - success
      branch:
        include:
          - develop
      event:
        include:
        - push

trigger:
  event:
    exclude:
    - tag

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
